src/bundle/DependencyInjection/Configuration.php, src/bundle/DependencyInjection/IbexaRestExtension.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1589](https://issues.ibexa.co/browse/IBX-1589)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#5
- ~Provided automated test coverage.~ // full stack Behat coverage
=> IBX-1589: Renamed Extension ez_publish_rest to ibexa_rest

tests/lib/Server/Input/Parser/Criterion/LogicalAndTest.php, tests/lib/Server/Input/Parser/Criterion/LogicalOrTest.php, tests/lib/Server/Output/ValueObjectVisitor/SectionListTest.php, tests/lib/Server/Output/ValueObjectVisitor/SectionTest.php, tests/lib/Server/Output/ValueObjectVisitor/URLAliasListTest.php, tests/lib/Server/Output/ValueObjectVisitor/URLAliasTest.php, tests/lib/Server/Output/ValueObjectVisitor/URLWildcardListTest.php, tests/lib/Server/Output/ValueObjectVisitor/URLWildcardTest.php
| **JIRA issue**     | [IBX-1334](https://jira.ez.no/browse/IBX-1334)
| **Target version** | Ibexa 4.0
This PR fixes incorrect namespace import - `Ibexa\Contracts\Core\Repository\Values\Content;` instead of `Ibexa\Core\Repository\Values\Content`. It is used as `Content\*` in the code, so was not clearly visible, though tests failed.
=> [Tests] Fixed incorrect import of Content Contract namespace

src/bundle/DependencyInjection/Compiler/FieldTypeProcessorPass.php, src/bundle/DependencyInjection/Compiler/InputHandlerPass.php, src/bundle/DependencyInjection/Compiler/InputParserPass.php, src/bundle/DependencyInjection/Compiler/OutputVisitorPass.php, src/bundle/DependencyInjection/Compiler/ValueObjectVisitorPass.php, src/bundle/Resources/config/input_parsers.yml, src/bundle/Resources/config/services.yml, src/bundle/Resources/config/value_object_visitors.yml, tests/bundle/DependencyInjection/Compiler/FieldTypeProcessorPassTest.php, tests/bundle/DependencyInjection/Compiler/InputHandlerPassTest.php, tests/bundle/DependencyInjection/Compiler/InputParserPassTest.php, tests/bundle/DependencyInjection/Compiler/OutputVisitorPassTest.php, tests/bundle/DependencyInjection/Compiler/ValueObjectVisitorPassTest.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1694](https://issues.ibexa.co/browse/IBX-1694)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#12
In this Pull Request we rename Ibexa's dependency injection container service tags according to the map provided by ibexa/compatibility-layer#12 as a part of the rebranding process. Backward compatibility for old service tags is provided by ibexa/compatibility-layer#12.
=> IBX-1694: Rebranded dependency injection container service tags

src/bundle/DependencyInjection/Compiler/FieldTypeProcessorPass.php, src/bundle/DependencyInjection/Compiler/InputHandlerPass.php, src/bundle/DependencyInjection/Compiler/InputParserPass.php, src/bundle/DependencyInjection/Compiler/OutputVisitorPass.php, src/bundle/DependencyInjection/Compiler/ValueObjectVisitorPass.php, src/bundle/DependencyInjection/Security/RestSessionBasedFactory.php, src/bundle/Resources/config/input_parsers.yml, src/bundle/Resources/config/routing.yml, src/bundle/Resources/config/security.yml, src/bundle/Resources/config/services.yml, src/bundle/Resources/config/value_object_visitors.yml, src/bundle/Routing/OptionsLoader/Mapper.php, src/lib/Input/ParserTools.php, tests/bundle/DependencyInjection/Compiler/FieldTypeProcessorPassTest.php, tests/bundle/DependencyInjection/Compiler/InputHandlerPassTest.php, tests/bundle/DependencyInjection/Compiler/InputParserPassTest.php, tests/bundle/DependencyInjection/Compiler/OutputVisitorPassTest.php, tests/bundle/DependencyInjection/Compiler/ValueObjectVisitorPassTest.php, tests/bundle/Routing/OptionsLoader/MapperTest.php, tests/lib/Server/Output/ValueObjectVisitor/PolicyTest.php
=> IBX-1853: Rebranded services names

src/bundle/DependencyInjection/IbexaRestExtension.php, src/bundle/Resources/config/default_settings.yml, src/bundle/Resources/config/services.yml
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1696](https://issues.ibexa.co/browse/IBX-1696)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#31
Rebranded service container parameter names and Ibexa Config Resolver namespaces to follow unified pattern
=> IBX-1696: Rebranded Container parameters and Config Resolver namespaces

src/lib/Server/Output/ValueObjectVisitor/Version.php
| **JIRA issue**     | [IBX-2264](https://issues.ibexa.co/browse/IBX-2264)
| **Target version** | Ibexa `v4.0`
Parent PR: https://github.com/ezsystems/ezplatform-rest/pull/91
=> Merge IBX-2264: Handled empty Thumbnail ProxyObject

src/lib/Server/Input/Parser/SortClause/DataKeyValueObjectClass.php
| **JIRA issue**     | [IBX-3757](https://issues.ibexa.co/browse/IBX-3757)
| **Target version** | `4.3`
Currently, there is no easy way to list Sort Clauses available for REST usage. Such need presented itself in Product Catalog as we want to inform the API consumer which Sort Clauses are available for product querying.
Ref: https://github.com/ibexa/product-catalog/pull/813/files#diff-9e5940343af2755db2be533fdc4dac336bd9810987adf7d99e3ef973676220baR174
**TODO**:
=> IBX-3757: Added `dataKey` getter allowing to identify REST Sort Clauses

src/bundle/Resources/config/routing.yml, src/lib/Server/Controller/SessionController.php, src/lib/Server/Controller/User.php, src/lib/Server/Values/UserSession.php, tests/bundle/Functional/HttpOptionsTest.php, tests/bundle/Functional/SessionTest.php, tests/bundle/Functional/TestCase.php, tests/bundle/Functional/UserTest.php
| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | [IBX-4043](https://issues.ibexa.co/browse/IBX-4043) |
| **Type**                                   | feature |
| **Target Ibexa version** | `v4.3` |
| **BC breaks**                          | no |
This PR adds new routes to REST API related to Ibexa Connect authentication needs.
* `[GET] /user/current` - redirects to current user load API.
* `[GET] /user/sessions/current` - return current User Session object.
They are necessary to explicitly confirm that user is logged in, without invoking any other route. 
Other routes may return information for anonymous users as well, so they are ill suited for this task (and it would be a …
=> IBX-4043: Added API current user / session routes

src/lib/Server/Input/Parser/Criterion.php
| **JIRA issue**     |
| **Target version** |
| **Tests pass**     | no
**TODO**:
=> Fixed usage of deprecated string interpolation (PHP 8.2)

composer.json, phpunit.xml, src/bundle/Resources/config/security.yml, src/contracts/Security/AuthorizationHeaderRESTRequestMatcher.php, tests/contracts/Security/AuthorizationHeaderRESTRequestMatcherTest.php
| **JIRA issue**     | [IBX-4259](https://issues.ibexa.co/browse/IBX-4359)
| **Target version** | `v4.3`
| **Doc needed**     | yes
This PR adds an additional service `Ibexa\Contracts\Rest\Security\AuthorizationHeaderRESTRequestMatcher` that can be used instead of `Ibexa\AdminUi\REST\Security\NonAdminRESTRequestMatcher`. 
The original issue stems from the fact that once it has been set as JWT firewall request matcher, it matched every time a REST request was issued, preventing cookie based authentication from working with our REST API endpoint.
What I'm suggesting instead is to detect a token-based authentication attempt (+ token creation …
=> IBX-4359: Added dedicated service for token-based authentication

src/lib/Server/Controller/SessionController.php
| **JIRA issue**     | [IBX-5024](https://issues.ibexa.co/browse/IBX-5024)
Fixes an issue where instead of providing the user with a valid CSRF token when `UserSession` is returned, we were simply passing the header value back.
**TODO**:
=> IBX-5024: Fixed CSRF source for UserSession response in `/user/session/check` endpoint

src/bundle/EventListener/ResponseListener.php, src/bundle/Resources/config/services.yml
| **JIRA issue**     | [IBX-5027](https://issues.ibexa.co/browse/IBX-5027)
Our REST API does not log exceptions when they occur, making it harder to debug requests.
While it is possible to read stacktrace in th REST response, it is cumbersome and requires response to actually remain somewhere (which might not always be the case).
Instead, I suggest we log exceptions in a similar fashion as built-in Symfony's ErrorListener service does it.
Ideally, we would simply allow ErrorListener to run and log exceptions this way (it registers itself with priority 0 and -128, for logging and …
=> IBX-5027: Added logging exceptions for REST

src/lib/Server/Output/ValueObjectVisitor/JWT.php
| **JIRA issue**     | [IBX-5025](https://issues.ibexa.co/browse/IBX-5025)
| **Doc needed**     | yes (REST API changes)
When responding to JWT endpoint, response contains token as an attribute:
```xml
<JWT token="value" />
```
or property prefixed with underscore
```json
{
"JWT": {
"_token": "value"
}
}
```
Given that token is an integral and important part of response, it should be passed as value:
```xml
<JWT>
<token>value</token>
</JWT>
```
or
```json
{
"JWT": {
"token": "value",
}
}
```
(old property `_token` is retained for BC)
**TODO**:
=> IBX-5025: Added `token` property to JWT response as object value

src/lib/Server/Input/Parser/Criterion/DateMetadata.php, tests/lib/Server/Input/Parser/Criterion/DateMetadataTest.php
| **JIRA issue**     | [IBX-5044](https://issues.ibexa.co/browse/IBX-5044)
Issue discovered when trying to provide a sample for:
https://github.com/ezsystems/developer-documentation/pull/1857
The following request towards /views endpoint will fail due to `DateMetadataCriterion.Value` being passed as string from the XML decoding service:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ViewInput>
<identifier>TitleView</identifier>
<Query>
<Filter>
<DateMetadataCriterion>
<Target>modified</Target>
<Value>1675681020</Value>
<Operator>gte</Operator>
</DateMetadataCriterion>
</Filter>
<limit>10</limit> …
```
=> IBX-5044: Fixed DateMetadata criterion failure in XML REST API

src/lib/Server/Input/Parser/Criterion.php
| **JIRA issue**     |
| **Target version** | e.g.: Ibexa `v4.3`
Fixes new PHP 8.2 deprecation notices:
`Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ...`
**TODO**:
=> Fixed deprecation notices in string interpolation with PHP 8.2

src/contracts/Output/Visitor.php
| **JIRA issue**     | [IBX-4929](https://issues.ibexa.co/browse/IBX-4929)
| **Target version** | 4.5, 4.4
| **Tests pass**     | N/A
The constructor was tagged as internal with the reason/description "param array $visitors", and excluded from PHP API Reference. This tag came from https://github.com/ezsystems/ezpublish-kernel/commit/51c1dc69b3be6002ceb0d867ffb15a963fbea92a#diff-d48f139271422b1fb63677449e8437d409fd636de439aba5afcb5530a76c7a82R108
Meaningless tag removed to include the constructor into the reference.
https://docs.phpdoc.org/3.3/guide/references/phpdoc/tags/internal.html
**TODO**:
=> IBX-4929: Removed `@internal param` PHPDoc from Output\Visitor

src/lib/Server/Controller/JWT.php
| **JIRA issue**     | [IBX-4929](https://issues.ibexa.co/browse/IBX-4929)
| **Target version** | 4.4+
| **Tests pass**     | n/a
The JWT controller is the only one in its namespace to be marked as internal and excluded from the PHPDoc.
The JWT controller has been marked as internal in https://github.com/kmadejski/ezplatform-rest/commit/0e809fe5ec9f612279b2ed56b06af83cc7f38e7b#diff-9c870b5da55481ce8b1de20af66b7b24e5352203473e50e814caab1b05c5b4a5R23 during https://github.com/ezsystems/ezplatform-rest/pull/54
* From a security POV, to document the JWT controller seems safe.
* From a developer POV, to have doc about the JWT controller might be …
=> IBX-4929: Removed @internal from Controller\JWT

src/bundle/Resources/config/services.yml, src/bundle/Serializer/SerializerFactory.php, src/lib/Output/Generator/Json/FieldTypeHashGenerator.php, src/lib/Output/Generator/Xml/FieldTypeHashGenerator.php, tests/lib/Output/Generator/FieldTypeHashGeneratorBaseTest.php, tests/lib/Output/Generator/Json/FieldTypeHashGeneratorTest.php, tests/lib/Output/Generator/Xml/FieldTypeHashGeneratorTest.php, tests/lib/Output/Generator/_fixtures/Json_FieldTypeHashGeneratorTest__testGenerateUsingNormalizer.out, tests/lib/Output/Generator/_fixtures/Json_FieldTypeHashGeneratorTest__testGenerateWithMissingNormalizer.out, tests/lib/Output/Generator/_fixtures/Xml_FieldTypeHashGeneratorTest__testGenerateUsingNormalizer.out, tests/lib/Output/Generator/_fixtures/Xml_FieldTypeHashGeneratorTest__testGenerateWithMissingNormalizer.out, tests/lib/Output/ValueObjectVisitorBaseTest.php
| **JIRA issue**     | [IBX-5296](https://issues.ibexa.co/browse/IBX-5296)
| **Doc needed**     | yes/no
This PR adds a new service: `ibexa.rest.serializer` (an instance of Symfony Serializer, dedicated for REST input/output).
My reasoning for this is as follows: we have expressed multiple times our desire to switch over from Visitors into Symfony Serializer for our REST API. While we cannot change the existing design (we cannot discard Visitors due to backwards compatibility promise at least), we could use Symfony Serializer for our new API's internally.
After all, our Generator currently requires an …
=> IBX-5296: Added REST serializer service

src/lib/FieldTypeProcessor/BaseRelationProcessor.php, tests/lib/FieldTypeProcessor/RelationProcessorTest.php
| **JIRA issue**     | [IBX-5387](https://issues.ibexa.co/browse/IBX-5387)
As the title states.
**TODO**:
=> IBX-5387: Handled not accessible Location in `RelationProcessor`

src/bundle/EventListener/UserCheckRequestListener.php, src/bundle/Exception/UnexpectedUserException.php, src/bundle/Resources/config/services.yml, tests/bundle/Functional/RootTest.php
| **JIRA issue**     | [IBX-5985](https://issues.ibexa.co/browse/IBX-5985)
| **Target version** | `v4.5` (can be backported?)
| **Doc needed**     | yes
This is PoC for handling of a special header to check that the user we are executing query with is the same as the REST client expects.
Handles cases where authentication has expired and we would otherwise receive a response for anonymous.
**TODO**:
=> IBX-5985: Added ability to check user against "X-Expected-User" header

composer.json
| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | n/a |
| **Type**                                   | improvement |
| **Target Ibexa version** | `v4.5`+ |
| **BC breaks**                          | no |
We have incorrect order of PSR-4 auto-loading of namespaces, putting legacy one, currently used for BC as the first one. While it doesn't affect the production code, it affects DX as PHPStorm doesn't seem to understand having multiple namespaces for one directory and expects the first one encountered. Additionally when creating new classes, it tries to use old namespace.
=> [Composer][DX] Changed order of namespace auto-loading

src/bundle/EventListener/RequestListener.php, src/bundle/RequestParser/Router.php, src/bundle/Resources/config/services.yml, src/bundle/UriParser/UriParser.php, src/contracts/UriParser/UriParserInterface.php, tests/bundle/EventListener/RequestListenerTest.php, tests/bundle/RequestParser/RouterTest.php, tests/integration/IbexaTestKernel.php, tests/integration/UriParser/UriParserTest.php
| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | [IBX-6222](https://issues.ibexa.co/browse/IBX-6222) |
| **Requires**         | #68 
| **Required by**   | ibexa/payment#109, ibexa/shipping#40
| **Type**                                   | bug |
| **Target Ibexa version** | `v4.5`+ |
| **BC breaks**                          | no |
Till now we had 2 ways of determining if a request was a REST one
- via listener which checked URI prefix e.g.: `/api/ibexa/v2` against the pattern and attached `is_rest_request` attribute.
- via Request Parser - to parse user input payloads[1] - based on route name beginning with `ibexa.rest`.
[1] e.g. to extract method identifier from such …
=> IBX-6222: Fixed Request Parser to include non-core routes as REST

phpstan-baseline.neon
| **Target version** | `4.6
This regenerates the PHPStan baseline for the current main branch, after merging 4.5 up.
**TODO**:
=> Fixed PHPStan baseline for 4.6

src/bundle/DependencyInjection/IbexaRestExtension.php, src/bundle/Resources/translations/repository_exceptions.en.xliff, src/lib/Server/Controller/Content.php, src/lib/Server/Controller/ContentType.php, src/lib/Server/Controller/Location.php, src/lib/Server/Controller/ObjectState.php, src/lib/Server/Controller/Role.php, src/lib/Server/Controller/Section.php, src/lib/Server/Controller/Trash.php, src/lib/Server/Controller/URLAlias.php, src/lib/Server/Controller/URLWildcard.php, src/lib/Server/Controller/User.php, src/lib/Server/Output/ValueObjectVisitor/ContentFieldValidationException.php
| **Target version** | Ibexa `v4.5`
| **Needs**     | https://github.com/ibexa/core/pull/237
**TODO**:
=> Added translation configuration

src/lib/Output/Generator/Json/FieldTypeHashGenerator.php, src/lib/Output/Generator/Xml/FieldTypeHashGenerator.php, tests/lib/Output/Generator/FieldTypeHashGeneratorBaseTest.php, tests/lib/Output/Generator/_fixtures/Json_FieldTypeHashGeneratorTest__testGenerateObjectUsingNormalizer.out, tests/lib/Output/Generator/_fixtures/Xml_FieldTypeHashGeneratorTest__testGenerateObjectUsingNormalizer.out
| **JIRA issue**     | [IBX-6640](https://issues.ibexa.co/browse/IBX-6640)
| **Target version** | Ibexa `v4.5`
When trying to fix an incorrect REST response shape, I have found out that the solution expected cannot work, because it relies on object being returned from Normalizer.
The incorrect response is (note the "data" property):
```json
{
"ActivityLogList": {
"_media-type": "application\/vnd.ibexa.api.ActivityLogList+json",
"_href": "\/api\/ibexa\/v2\/activity_log\/view",
"ActivityLog": [
{
"_media-type": "application\/vnd.ibexa.api.ActivityLog+json",
"object_id": "test_object_id",
"object_class": "stdClass",
"action": …
```
=> IBX-6640: Fixed infinite loop when Normalizer returns an object

phpstan-baseline.neon, src/bundle/Resources/config/input_parsers.yml, src/lib/Input/ParserTools.php, src/lib/Server/Exceptions/ValidationFailedException.php, src/lib/Server/Input/Parser/Criterion/Image.php, src/lib/Server/Input/Parser/Criterion/ImageDimensions.php, src/lib/Server/Input/Parser/Criterion/ImageFileSize.php, src/lib/Server/Input/Parser/Criterion/ImageMimeType.php, src/lib/Server/Input/Parser/Criterion/ImageOrientation.php, src/lib/Server/Validation/Builder/Input/Parser/BaseInputParserCollectionValidatorBuilder.php, src/lib/Server/Validation/Builder/Input/Parser/BaseInputParserValidatorBuilder.php, src/lib/Server/Validation/Builder/Input/Parser/Criterion/BaseImageCriterionValidatorBuilder.php, src/lib/Server/Validation/Builder/Input/Parser/Criterion/ImageCriterionValidatorBuilder.php, src/lib/Server/Validation/Builder/Input/Parser/Criterion/ImageDimensionsCriterionValidatorBuilder.php, src/lib/Server/Validation/Builder/Input/Parser/Criterion/ImageFileSizeCriterionValidatorBuilder.php, src/lib/Server/Validation/Builder/Input/Parser/Criterion/ImageMimeTypeCriterionValidatorBuilder.php, src/lib/Server/Validation/Builder/Input/Parser/Criterion/ImageOrientationCriterionValidatorBuilder.php
| **JIRA issue**     | [IBX-6620](https://issues.ibexa.co/browse/IBX-6620)
| **Type**| feature
| **Target version** | `v4.6`
| **Tests pass**     | yes/no
| **Doc needed**     | yes
This PR adds new criteria parsers that allows to search images by REST. 
Criterion to filter by image size.
`min` - Optional, minimum file size in MB
`max` - Optional maximum file size in MB
```json
"ImageFileSizeCriterion": {
"fieldDefIdentifier": "<field_definition_identifier>",
"size": {
"min": 0 
"max": 2
}
}
```
Criterion to filter by image mime type.
`type` - string or array
```json
"ImageMimeTypeCriterion": {
"fieldDefIdentifier": "<field_definition_identifier>",
"type": "image/jpeg"
}
```
OR 
```json …
```
=> IBX-6620: Added image criterions rest input parsers

phpstan-baseline.neon, src/contracts/Input/Parser.php
| :ticket: Issue | N/A |
- https://github.com/ibexa/admin-ui/pull/1161
This PR adds missing declaration for `Ibexa\Contracts\Rest\Input\Parser::parse`, which will make it so it's not necessary to provide this declaration to descendants.
QA is not necessary.
Documentation is not necessary.
=> Added proper PHPStan declaration to `Ibexa\Contracts\Rest\Input\Parser::parse`

.github/workflows/ci.yaml, .github/workflows/integration-tests-callable.yaml, composer.json
| :ticket: Issue | IBX-8119 |
This PR bumps the minimum required version of PHP to 8.3.
`>=8.3` version constraint is set with expectation of compatibility with version PHP 9.
Additionally, this PR:
* enforces sorting of packages within `require` and `require-dev` sections of composer.json file
* replaces `~5.0.0@dev` declarations with their more development friendly `~5.0.x-dev`.
* adjusts github workflows to match new PHP version
* updates GH action versions
=> IBX-8119: Upgraded minimum PHP version to 8.3

phpstan-baseline.neon, phpstan.neon, src/contracts/Input/ParsingDispatcher.php
| :ticket: Issue | n/a |
Fixed outstanding PHPStan-reported issues on 4.6:
=> [PHPStan] Fixed parser list type hinting in ParserDispatcher

src/bundle/Resources/config/routing.yml, src/lib/Server/Controller/SessionController.php
| :ticket: Issue | IBX-8290 |
As part of re-implementing REST authorization compliant with the new Symfony authenticator mechanism I decided to deprecate `ibexa.rest.refresh_session` route as there is already `ibexa.rest.check_session` which does similar thing and has better usage. It will be removed as part of `5.0` targetting PR.
Please mark this endpoint in REST API reference as deprecated and mention that `ibexa.rest.check_session` should be used instead.
=> IBX-8290: Deprecated `ibexa.rest.refresh_session` route in favor of `ibexa.rest.check_session`

phpstan-baseline.neon, src/bundle/Resources/config/routing.yml, src/bundle/Resources/config/services.yml, src/bundle/Routing/ExpressionLanguage/ContentTypeHeaderMatcherExpressionFunction.php, src/bundle/Routing/OptionsLoader/Mapper.php, src/contracts/Input/MediaTypeParser.php, src/contracts/Input/MediaTypeParserInterface.php, tests/bundle/Functional/HttpOptionsTest.php, tests/bundle/Routing/ExpressionLanguage/ContentTypeHeaderMatcherExpressionFunctionTest.php, tests/bundle/Routing/OptionsLoader/RouteCollectionMapperTest.php, tests/lib/Input/MediaTypeParserTest.php
| :ticket: Issue | IBX-8173|
As agreed internally to avoid methods' duplication a new routing expression language function was implemented that allows parsing media type value from the `Content-Type` header.
Usage:
```yaml
condition: 'ibexa_get_media_type(request) === "CopyContentTypeInput"'
```
Additionally, it was used to make copy content type endpoint OpenAPI compatible.
```
POST /api/v2/ibexa/content/types/1
Content-Type: application/vnd.ibexa.api.CopyContentTypeInput+json
Accept: application/json
{
"CopyContentTypeInput": {}
}
```
=> IBX-8173: Implemented routing language expression parsing media type from `Content-Type` header

src/bundle/Resources/config/routing.yml, src/lib/Server/Controller/Trash.php, tests/bundle/Functional/HttpOptionsTest.php, tests/bundle/Functional/TrashTest.php
| :ticket: Issue | IBX-8368 |
https://github.com/ibexa/rest/pull/100
The new endpoint follows the given specification:
```
POST|TRASH /api/ibexa/v2/content/locations/1/2/71
Content-Type: application/vnd.ibexa.api.TrashLocationInput+json
Accept: application/json
{
"TrashLocationInput": {}
}
```
TBD
=> IBX-8368: Implement dedicated location trashing endpoint

src/lib/Server/Controller/Trash.php, tests/bundle/Functional/TrashTest.php
| :ticket: Issue | IBX-8174 |
Please see https://doc.ibexa.co/en/4.6/api/rest_api/rest_api_reference/rest_api_reference.html#managing-content-untrash-content-item. The only difference is that the endpoint will throw 403 if original location doesn't exist.
Trash content and its parent and then try to restore trash item without using the `destination` parameter.
TBD
=> IBX-8174: Fixed restore trash item response codes to match the spec

src/lib/Server/Input/Parser/Criterion/UserMetadata.php
| :ticket: Issue | n/a |
|----------------|-----|
After PHPStan release we're getting new issue reported:
```
------ ------------------------------------------------------------------------- 
Line   src/lib/Server/Input/Parser/Criterion/UserMetadata.php                   
------ ------------------------------------------------------------------------- 
51     Parameter #2 $str of function explode expects string, int|string given.  
------ ------------------------------------------------------------------------- 
```
Seems there's an easy fix. This PR in general improves UserMetadata criterion parser code quality.
Change to CS & internal code, no QA required.
=> [CS] Improved implementation of UserMetadata criterion parser

src/bundle/Resources/config/services.yml, src/contracts/Input/Parser/Query/Criterion/BaseCriterionProcessor.php, src/contracts/Input/Parser/Query/Criterion/CriterionProcessorInterface.php
| :ticket: Issue | [IBX-8596](https://issues.ibexa.co/browse/IBX-8596) |
- https://github.com/ibexa/admin-ui/pull/1290
- https://github.com/ibexa/shipping/pull/77
This PR adds `BaseCriterionProcessor` to avoid duplicating code in several packages like:
- https://github.com/ibexa/shipping/blob/main/src/lib/REST/Input/Query/Criterion/Shipment/CriterionProcessor.php
- https://github.com/ibexa/product-catalog/blob/main/src/bundle/REST/Input/Parser/Query/Criterion/CriterionProcessor.php#L33
- https://github.com/ibexa/admin-ui/pull/1290/files#diff-d0e26b42697c26866438f1e43992d8e8a20da300a11b2a56baa4c308a915ea1b
BaseCriterionProcessor is used to parse criteria.
=> IBX-8596: Added BaseCriterionProcessor

src/contracts/Input/Parser/Query/Criterion/BaseCriterionProcessor.php
| :ticket: Issue | IBX-8596 |
- #116
- blocks CI of #118
Not sure if this was intentional, but seems we're missing `declare(strict_types=1)` in `BaseCriterionProcessor` introduced via #116.
On `main` it causes [code style check failure](https://github.com/ibexa/rest/actions/runs/10603436002/job/29387755775?pr=118#step:5:16) and blocks CI of #118.
=> Added missing strict types declaration to BaseCriterionProcessor

src/bundle/Resources/config/services.yml
| :ticket: Issue | IBX-8603 |
- https://github.com/ibexa/connector-ai/pull/21
Allow deeper media-type granulation, like ie. `application/vnd.ibexa.api.ai.DoSomething+json`. Otherwise we would need to distingish mediatypes with prefix, like `AIDoSomething`. While `DoSomething` is meaningless example; PR makes more sense if we consider `application/vnd.ibexa.api.ai.CreateContent+json` a possible and valid feature.
Change is BC safe.
=> IBX-8603: Allow deeper media-type granulation

phpstan-baseline.neon, src/bundle/DependencyInjection/Configuration.php, src/bundle/DependencyInjection/IbexaRestExtension.php, src/bundle/Resources/config/services.yml, src/lib/Output/Generator/Json/FieldTypeHashGenerator.php, src/lib/Output/Generator/Xml/FieldTypeHashGenerator.php
| :ticket: Issue | IBX-8825 |
This PR introduces the concept of `strict_mode` for REST.
In `strict_mode`, when REST processing encounters an error/exception that it previously silenced (and usually logged as an error) it will re-throw it.
> [!NOTE]
> This functionality needs to be tested separately on `prod` and `dev` application environments.
=> IBX-8825: Added `strict_mode` for REST API

src/bundle/Resources/config/services.yml, src/contracts/Input/Parser/Query/SortClause/BaseSortClauseProcessor.php, src/contracts/Input/Parser/Query/SortClause/SortClauseProcessorInterface.php
| :ticket: Issue | [IBX-8597](https://issues.ibexa.co/browse/IBX-8597) |
- https://github.com/ibexa/shipping/pull/77
- https://github.com/ibexa/product-catalog/pull/1171
This PR adds `BaseSortClauseProcessor` to avoid duplicating code in several packages like:
- https://github.com/ibexa/shipping/blob/main/src/lib/REST/Input/Query/SortClause/Shipment/SortClauseProcessor.php
- https://github.com/ibexa/product-catalog/blob/main/src/bundle/REST/Input/Parser/Query/Criterion/CriterionProcessor.php#L52
BaseSortClauseProcessor is used to parse sort clauses.
=> IBX-8597: Added BaseSortClauseProcessor

src/lib/RequestParser.php, src/lib/RequestParser/EzPublish.php, src/lib/RequestParser/Pattern.php
| :ticket: Issue | IBX-8535 |
During removing deprecated `\Ibexa\Bundle\Rest\RequestParser\Router` it turned out, it does not make much sense to keep interface and other unused implementations.
=> IBX-8535: Deprecate RequestParser and implementations

phpstan-baseline.neon, src/lib/Server/Controller/User.php
=> IBX-8534: Dropped usage of deprecated contentService::loadContentDrafts method

phpstan-baseline-7.4.neon, phpstan-baseline-8.0.neon, phpstan-baseline.neon
| :ticket: Issue | N/A |
Updates to PHPStan and deprecation removals (I assume) triggered some changes in error list in PHPStan.
=> Regenerated PHPStan baseline files

.php-cs-fixer.php, phpstan-baseline.neon, src/contracts/Output/Exceptions/AbstractExceptionVisitor.php, src/lib/Server/Output/ValueObjectVisitor/Exception.php
| :ticket: Issue | IBX-8784 |
This PR enables child Exception visitors to more easily control exception message and description presented by REST endpoints.
=> IBX-8784: Added `AbstractExceptionVisitor` template to allow fine-grained control of output

composer.json, phpstan-baseline.neon, src/contracts/Output/ValueObjectVisitor.php, src/lib/FieldTypeProcessor/ImageProcessor.php, src/lib/Input/ParserTools.php, src/lib/Server/Controller/Content.php, src/lib/Server/Input/Parser/Query.php, tests/lib/FieldTypeProcessor/ImageProcessorTest.php
| :ticket: Issue | IBX-8534 |
- https://github.com/ibexa/core/pull/456
=> IBX-8534: Change deprecated path to inputUri 

src/contracts/Exceptions/NotFoundException.php
- ibexa/core#463
- ibexa/payment#161
- `Ibexa\Contracts\Rest\Exceptions\NotFoundException`
- [Before](https://doc.ibexa.co/en/latest/api/php_api/php_api_reference/classes/Ibexa-Contracts-Rest-Exceptions-NotFoundException.html) has a not-rendered `@see` in its summary.
- [After](https://ez-systems-developer-documentation--2583.com.readthedocs.build/en/2583/api/php_api/php_api_reference/classes/Ibexa-Contracts-Rest-Exceptions-NotFoundException.html) has a new summary, and description with a link.
A DocBlock summary line can't have formatting, it isn't rendered.
Add missing summary line for proper rendering.
See ibexa/core#463 for more.
=> Enhance PHPDoc

composer.json, phpstan-baseline.neon, src/bundle/Resources/config/routing.yml, src/bundle/Resources/config/services.yml, src/lib/Security/Authenticator/RestAuthenticator.php, src/lib/Server/Controller.php, src/lib/Server/Controller/Content.php, src/lib/Server/Controller/SessionController.php, src/lib/Server/Controller/User.php, tests/integration/UriParser/UriParserTest.php, tests/lib/Output/VisitorTest.php, tests/lib/Server/Output/ValueObjectVisitor/RestExecutedViewTest.php
> [!CAUTION]
> This is a part of bigger set of changes, to be merged together when ready
> - [x] :exclamation:  **Remove TMP commits before merge** :exclamation:
| :ticket: Issue | IBX-8470 |
- https://github.com/ibexa/core/pull/447
- https://github.com/ibexa/doctrine-schema/pull/27
- https://github.com/ibexa/test-core/pull/13
This PR bumps Symfony to v6 with necessary codebase upgrades.
Please take a look at `RestAuthenticator` changes. `getPassword` method is completely gone from `UserInterface`, without any replacement, so not sure what will be end result of that change. Temporarily placed empty string there.
I'll need to go back to REST Functional tests once full-stack app is upgraded.
Key changes:
Sanities in the form of regression tests.
No …
=> IBX-8470: Upgraded codebase to Symfony 6

src/bundle/Resources/config/routing.yml, src/bundle/Routing/OptionsLoader/Mapper.php, tests/bundle/Functional/BookmarkTest.php, tests/bundle/Functional/LocationTest.php, tests/bundle/Routing/OptionsLoader/MapperTest.php
| :ticket: Issue | IBX-9587 |
- https://github.com/ibexa/rest/pull/138
This is a follow-up to Symfony 6 upgrade (#138). Fixing issues that surfaced via the functional tests after merging full-stack app.
`OPTIONS` requests controller mapper used obsolete single-colon controller reference that stopped working in Symfony 6.
`SessionController::refreshSessionAction` controller used obsolete single-colon reference as well.
- `LocationTest` created suffix using mismatched case in one place `testCreatelocation` instead of `testCreateLocation` which made tests fail on PostgreSQL instance (not visible in tests, noticed by accident). In short: it created `testCreateLocation*` remote ID but queried for `testCreatelocation*` remote ID, which doesn't work on …
=> IBX-9587: Fixed failing REST requests after Symfony 6 upgrade

.github/workflows/ci.yaml, composer.json, phpstan-baseline.neon, rector.php, src/bundle/EventListener/UserCheckRequestListener.php, src/contracts/Output/VisitorAdapterNormalizer.php, src/lib/Security/AuthorizationHeaderRESTRequestMatcher.php, src/lib/Security/JWTTokenCreationRESTRequestMatcher.php
| :ticket: Issue | IBX-9584  |
Enabled and executed automatic refactoring rules defined for Symfony 6.x.
* [HTTP] Replaced deprecated usage of Symfony\Component\HttpFoundation\RequestMatcher
* [Security] Replaced deprecated usage of Symfony\Component\Security\Core\Security
* [Serializer] Fixed usages of deprecated Symfony\Component\Serializer\Normalizer{ContextAwareDenormalizerInterface, ContextAwareNormalizerInterface};
Additionally added rector job to CI setup to prevent merging up code which is not compatible with Symfony 6+.
Sanities.
N/A
=>  IBX-9584: Resolved Symfony 6.x deprecations

src/bundle/Resources/api_platform/schemas/base_schemas.yml, src/bundle/Resources/api_platform/schemas/content_types_schemas.yml, src/bundle/Resources/api_platform/schemas/language_schemas.yml
| :ticket: Issue | IBX-9058 |
- `nullable` was specific to only OpenAPI 3.0
- `null` is new in OpenAPI 3.1
=> IBX-9058: Adapt schemas to OpenAPI 3.1

src/bundle/ApiPlatform/OpenApiFactory.php
| :ticket: Issue | IBX-9058 |
- #156
- #157
- #159
=> IBX-9058: Set OpenAPI schema info

src/bundle/Resources/api_platform/schemas/base_schemas.yml, src/bundle/Resources/api_platform/schemas/bookmarks_schemas.yml, src/bundle/Resources/api_platform/schemas/content_locations_schemas.yml, src/bundle/Resources/api_platform/schemas/content_objects_schemas.yml, src/bundle/Resources/api_platform/schemas/content_trash_schemas.yml, src/bundle/Resources/api_platform/schemas/content_type_groups_schemas.yml, src/bundle/Resources/api_platform/schemas/content_types_schemas.yml, src/bundle/Resources/api_platform/schemas/content_url_aliases_schemas.yml, src/bundle/Resources/api_platform/schemas/object_state_groups_schemas.yml, src/bundle/Resources/api_platform/schemas/root_schemas.yml, src/bundle/Resources/api_platform/schemas/user/roles_schemas.yml, src/bundle/Resources/api_platform/schemas/user/sessions_schemas.yml, src/bundle/Resources/api_platform/schemas/user/user_groups_schemas.yml, src/bundle/Resources/api_platform/schemas/user/users_schemas.yml, src/bundle/Resources/api_platform/schemas/views_schemas.yml
| :ticket: Issue | IBX-9058 |
Same fix:
- ibexa/calendar#70
- ibexa/cart#122
- ibexa/corporate-account#284
- ibexa/order-management#147
- ibexa/product-catalog#1286
- ibexa/shipping#107
- ibexa/taxonomy#323
Same ticket:
- #156
- #157
- #158
Fix some `redocly lint` errors
- ```
`type` can be one of the following only: "object", "array", "string", "number", "integer", "boolean", "null".
```
- `Error: Objects are not valid as a React child (found: object with keys {type, required, properties}). If you meant to render a collection of children, use an array instead.`
- `Error: Objects are not valid as a React child (found: object with keys {oneOf}). If you meant to render a collection of children, use an array instead.`
=> IBX-9058: Fix OpenApi type/$ref/oneOf usage

src/bundle/ApiPlatform/OpenApiFactory.php, src/bundle/Resources/api_platform/schemas/views_schemas.yml, src/lib/Server/Controller/User/UserListController.php, src/lib/Server/Controller/User/UserVerifyController.php
| :ticket: Issue | IBX-9058 |
- ibexa/segmentation#125
- ibexa/cart#124
- ibexa/documentation-developer#2674
- Fix JSON examples (see below)
- Add LocationQuery (which extend Query)
- Fix typo "visibile" → "visible"
In Redocly output, while XML examples are OK, JSON examples are one-lined with `\n`. It seems that an object example should be a YAML object, not a single JSON string. I didn't find an `example:` example but this is how `examples:` works according to specifications and https://redocly.com/learn/openapi/openapi-visual-reference/example. The fix help to have JSON well interpreted in the Redocly output, an unfoldable object easier to navigate.
Before, without the fix:
After, with the fix:
=> IBX-9058: Complete REST API

src/lib/Output/Normalizer/JsonObjectNormalizer.php
| :ticket: Issue | N/A |
- https://github.com/ibexa/connector-ai/pull/118
Currently, an empty array is returned instead of an object. AbstractObjectNormalizer in a similar case also returns ArrayObject
```
if ($preserveEmptyObjects && !$data) {
return new \ArrayObject();
}
return $data;
```
The issue is visible in https://github.com/ibexa/connector-ai/actions/runs/13882215491/job/38842242488.
The `preserve_empty_objects` flag will be set into context by `[src/lib/REST/Output/Normalizer/PreserveEmptyObjectNormalizer.php](https://github.com/ibexa/rest/pull/165/files#diff-252f4432e1b58cf174a022d3d3bc98a2462016cf7638fbc301c7791498cbee64)`
=> Fixed an issue when empty array was return instead of object

src/lib/Server/Controller/Content/ContentVersionRelationDeleteController.php, src/lib/Server/Output/ValueObjectVisitor/RestRelation.php
| :ticket: Issue | IBX-9103 |
See https://github.com/ibexa/core/pull/524. Unblocks https://github.com/ibexa/rest/pull/164 
N/A
N/A
=> IBX-9103: Replaced Relation const calls with RelationType enum

phpstan-baseline.neon, src/bundle/Resources/config/serializer.yaml, src/contracts/Output/VisitorAdapterNormalizer.php
Pass already called context to `VisitorAdapterNormalizer` in `normalize` method so we are not hit with infinite recursion.
=> Fixed infinite recursion in serializer

phpstan-baseline.neon, src/lib/Server/Controller/Content.php
| :ticket: Issue | IBX-8677 |
https://github.com/ibexa/taxonomy/pull/356
=> IBX-8677: Cast location to integer in copying content action

phpstan-baseline.neon, src/lib/Server/Controller/Location.php
| :ticket: Issue | n/a |
|----------------|-----|
New day, new PHPStan release. Uncovered a potentially fatal error when strict types are enforced in Location redirect controller. [Visible on 5.0.x-dev](https://github.com/ibexa/rest/actions/runs/17797131143/job/50587324689?pr=197#step:5:18), but exists on 4.6. Seems for some reason on 5.0.x-dev the issue was not detected after refactoring controllers. 
Fixed on 4.6 instead of re-adding to the baseline on main.
=> Added cast to `int` when trying to load a location in Location redirect controller
